baseURL = 'https://pikwaii93.github.io/Hugo-class/'
languageCode = 'fr-fr'
title = 'Spider-Cat Website'
theme = "ananke"
resourceDir = "../resources"
disqusShortname = false

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "SpidercatğŸ±ğŸ•¸ï¸"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.fr]
    title = "SpidercatğŸ±ğŸ•¸ï¸"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["css/custom.css"]
  commentoEnable = false
  text_color = "white"
  author = "SpidercatğŸ±ğŸ•¸ï¸"
  favicon = ""
  site_logo = ""
  description = "Premier projet Hugo HETIC 2023"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 3
  # ParamÃ¨tres spÃ©cifiques au thÃ¨me Ananke
  showReadingTime = true
  featured_image = '/images/banner.jpg'

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/watch?v=GBIIQ0kP15E"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/PiKwaii93"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/maxence.nho/"

